/**
 * Author: Exenreco Bell
 *
 * Title: server.js
 *
 * Date: June 6, 2024
 *
 * Description: Application setup. Autogenerated using Express generator.
 *
 * Version: 1.0
 */

'use strict';

// Importing required modules
import logger from 'morgan';
import express from 'express';
import cookieParser from 'cookie-parser';
import { notFoundHandler, errorHandler } from './core/middleware.js';
import { serverRoutes } from './routes/routes.js';

// Variable declaration for the express server
let server = express();

// CORS configuration
server.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*'); // This allows all origins
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS'); // Allowed request methods
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept'); // Allowed headers
  next();
});

// Express server configuration
server.use(logger('dev'));
server.use(express.json());
server.use(express.urlencoded({ extended: false }));
server.use(cookieParser());

// configure server routes
if( serverRoutes && typeof serverRoutes === 'object' )
  Object.entries(serverRoutes).forEach(([route, options]) => {
    server.use(`/${route || ''}`, options?.router || null);
  });
else
  throw new Error('Server routes could not be imported from all.routes.js or is not an object');

// Use the error handling middleware
server.use(notFoundHandler);
server.use(errorHandler);

// Export the server
export { server };
